gravity: 9.81
mu_ground: 1.0
mu_block: 0.0

m_ee: 0.37
m_block: 1.0

r_ee: 0.0725
xlen_block: 0.1
ylen_block: 0.1
zlen_block: 0.1

block_init: [0.8, 0.447]

ee_init: [0.5, 0.43]
ee_des: [0.5, 0.484]

block_init: [0.65, 0.485]