"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmt_robot_input(object):
    __slots__ = ["utime", "num_efforts", "effort_names", "efforts"]

    __typenames__ = ["int64_t", "int32_t", "string", "double"]

    __dimensions__ = [None, None, ["num_efforts"], ["num_efforts"]]

    def __init__(self):
        self.utime = 0
        self.num_efforts = 0
        self.effort_names = []
        self.efforts = []

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_robot_input._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_efforts))
        for i0 in range(self.num_efforts):
            __effort_names_encoded = self.effort_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__effort_names_encoded)+1))
            buf.write(__effort_names_encoded)
            buf.write(b"\0")
        buf.write(struct.pack('>%dd' % self.num_efforts, *self.efforts[:self.num_efforts]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_robot_input._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_robot_input._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmt_robot_input()
        self.utime, self.num_efforts = struct.unpack(">qi", buf.read(12))
        self.effort_names = []
        for i0 in range(self.num_efforts):
            __effort_names_len = struct.unpack('>I', buf.read(4))[0]
            self.effort_names.append(buf.read(__effort_names_len)[:-1].decode('utf-8', 'replace'))
        self.efforts = struct.unpack('>%dd' % self.num_efforts, buf.read(self.num_efforts * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcmt_robot_input in parents: return 0
        tmphash = (0x5ed0a6207a3572ae) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmt_robot_input._packed_fingerprint is None:
            lcmt_robot_input._packed_fingerprint = struct.pack(">Q", lcmt_robot_input._get_hash_recursive([]))
        return lcmt_robot_input._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_robot_input._get_packed_fingerprint())[0]

