gravity: 9.81
mu_ground: 0.1
mu_block: 0.4615

m_ee: 0.1
m_block: 0.5

r_ee: 0.001 # for visual to change, have to change in visuals file rn
xlen_block: 0.5
ylen_block: 0.16
zlen_block: 0.1

ee_init: [-0.1, 0.2]
ee_des: [-0.3, 0.2]

block_init: [0.0, 0.06]
block_des: [1.0, 0.05]