gravity: 9.81
mu_world: 0.4
mu_joint: 0.0

m_ee: 0.37
m_tray: 1.0

r_ee: 0.0725
d_ee: 0.01
r_tray: 0.2286
d_tray: 0.022

supp_pos: [0.8, 0.447]
supp_xdim: 0.4
supp_ydim: 0.8
supp_zdim: 0.05

ee_init: [0.5, 0.43]
ee_des: [0.5, 0.484]

tray_init: [0.65, 0.485]